          
			  <div class="col-md-4"><img src="LinjieLyu.jpg" class="img-responsive" width="180" height="240" alt="Firstname Lastname" /></div>
              <div class="col-md-8"><h3>Linjie Lyu</h3>
			    
                <a href="//www.mpi-inf.mpg.de/">Max-Planck-Institut f&uuml;r Informatik</a><br />
                <a href="" title="D6: Visual Computing and Artificial Intelligence">D6: Visual Computing and Artificial Intelligence</a><br />      
				<b style="color:rgb(255,0,0);"> I will graduate this year and am looking for Reasearch scientist and postdoc positions.</b>
                <table class="table">
                  <tr>
                    <td><i class="fa fa-map-marker"></i>&nbsp;office:</td>
                    <td><div id="floorplan-modal" class="modal fade" tabindex="-1" style="display: none;"></div>
                      <a href="//www.mpi-inf.mpg.de/institute/address">Campus E1 4</a>,
                      Room 117<br/>
                      Saarland Informatics Campus<br/>
                      66123 <a href="http://www.saarbruecken.de/">Saarbr&uuml;cken</a><br/>
                      <a href="http://www.deutschland.de/">Germany</a></td>
                  </tr>
                  <tr>
                    <td><i class="fa fa-envelope"></i>&nbsp;email:</td>
                    <td>  <!--#if expr="$REMOTE_ADDR = /139\.19\..*\..*/" -->
      <!-- CORRECT HERE:                                                       -->
      <!-- this is visible only from inside the institute.                     --> 
      <!-- It's convenient for everyone in the institute.                      -->
      <!-- That way spammers can not harvest your email address                -->

       <a href="mailto:llyu@mpi-inf.mpg.de">llyu@mpi-inf.mpg.de</a><br />
			
  <!--#else -->
      <!-- CORRECT HERE: Your personal URL can be found on the people page     -->
      <!-- How to find the unique URL for your email address:                  -->
      <!-- 1. Open in your browser:                                            --> 
      <!--          http://people.mpi-inf.mpg.de/people/index.html             -->
      <!-- 2. Find your name entry on that page                                -->
      <!-- 3. Copy the URL from the Email column that reads "Retrieve email"   --> 
      <!--    Tip: - Right click on the linked text "Retrieve email"           -->
      <!--         - and "Copy Link Location"                                  -->
      <!-- 4. Paste/Put this copied URL into the href-anchor tag below         -->
	  <!-- <a href="mailto:llyu@mpi-inf.mpg.de">llyu@mpi-inf.mpg.de</a><br />  -->
      <a href="https://domino.mpi-inf.mpg.de/intranet/mpii/people.nsf/email!ReadForm&UID=23151&Name=Lyu%2C%20Linjie&">Get my email address via email</a><br />

  <!--#endif -->
                   </td>
                  </tr>
                  <tr>
                    <td><i class="fa fa-phone"></i>&nbsp;phone:</td>
                    <td>+49 681 9325 4548
</td>
                  </tr>
                  <tr>
                    <td><i class="fa fa-fax"></i>&nbsp;fax:</td>
                    <td>+49 681 9325-4099</td>
                  </tr>
                </table>
              </div>
